server:
  port: 9292

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: rabin-group-1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer